version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
    timezone: "Asia/Ho_Chi_Minh"
  labels:
    - "dependencies"
  open-pull-requests-limit: 50
